name: Chromatic

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to run Chromatic for (e.g., production, staging)"
                required: true
                default: "production"

jobs:
    chromatic:
        name: Run Chromatic
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Run Chromatic
              id: chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  exitOnceUploaded: true
                  autoAcceptChanges: ${{ github.event.inputs.environment == 'production' }}
                  onlyChanged: true
                  skip: ${{ github.event.inputs.environment != 'production' }}

            - name: Report Chromatic Results
              if: always()
              run: |
                  echo "Chromatic build results: ${{ steps.chromatic.outputs.buildUrl }}"
                  echo "Storybook preview: ${{ steps.chromatic.outputs.storybookUrl }}"
